### ISSUE TITLE
Admin Area not existent?

### ISSUE THREAD

**Issue by darknessresides** [UploadX/UploadX#13]
I can't get in to the admin area even on several fresh installs of this. Either I'm doing something wrong or I don't see anything that pertains to the admin area in all of the files. Also can you please update the install instructions?

**Comment by Pips801** [comment]
Hi @darknessresides, can we get more information as to your current setup? Do you have nginx or apache? What operating system are you on? Are you running this on your own website? Have you tried going to `<directory>/admin/` and tried the password `password`?

**Comment by darknessresides** [comment]
Apache and it's on Ubuntu 12.04. I've tried going to that link which it doesn't go. Give's this error:

Not Found

The requested URL /admin/ was not found on this server.

**Comment by Pips801** [comment]
If you go to the root directory of UploadX, what do you see?

**Comment by darknessresides** [comment]
docs/lib/res/ folders

**Comment by Pips801** [comment]
Can you post a screenshot of what you see for us?

**Comment by darknessresides** [comment]
http://i.imgur.com/RCx66uv.png

**Comment by darknessresides** [comment]
If you'd like you can contact me via Skype and we can speak there.

**Comment by Pips801** [comment]
Have you turned on mod_rewrite in apache?

`a2enmod rewrite`
`service apache2 restart`

**Comment by Pips801** [comment]
Also, make sure to chown the directory to www-data:www-data

**Comment by darknessresides** [comment]
Just did and still the same

**Comment by Pips801** [comment]
Have you actually installed and configured PHP? It's giving a 500 error on any php document.

**Comment by darknessresides** [comment]
PHP is on a fresh install by default. It's PHP5 if I recall. Info can be found here: http://drakoni.tech/phpinfo.php

**Comment by Pips801** [comment]
Can you please post the contents of `/var/log/apache2/error.log`?

**Comment by darknessresides** [comment]
`[Thu Sep 29 19:42:53 2016] [error] [client 50.37.195.225] PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phpJr5XnD' to '/var/www/Test.png' in /var/www/index.php on line 36
[Thu Sep 29 19:43:07 2016] [error] [client 50.37.195.225] (13)Permission denied: file permissions deny server access: /var/www/index.html
[Thu Sep 29 19:43:36 2016] [error] [client 50.37.195.225] (13)Permission denied: file permissions deny server access: /var/www/index.html
[Thu Sep 29 19:45:43 2016] [error] [client 50.37.195.225] (13)Permission denied: file permissions deny server access: /var/www/index.html
[Thu Sep 29 19:45:46 2016] [error] [client 50.37.195.225] (13)Permission denied: file permissions deny server access: /var/www/index.html
[Thu Sep 29 19:49:46 2016] [error] [client 50.37.195.225] File does not exist: /var/www/admin
[Thu Sep 29 20:05:39 2016] [notice] caught SIGTERM, shutting down
[Thu Sep 29 20:05:40 2016] [notice] Apache/2.2.22 (Ubuntu) PHP/5.3.10-1ubuntu3.24 with Suhosin-Patch configured -- resuming normal operations
[Thu Sep 29 20:06:02 2016] [error] [client 50.37.195.225] File does not exist: /var/www/admin
[Thu Sep 29 20:07:39 2016] [notice] caught SIGTERM, shutting down
[Thu Sep 29 20:07:40 2016] [notice] Apache/2.2.22 (Ubuntu) PHP/5.3.10-1ubuntu3.24 with Suhosin-Patch configured -- resuming normal operations
[Thu Sep 29 20:07:45 2016] [error] [client 50.37.195.225] File does not exist: /var/www/admin
[Thu Sep 29 20:07:48 2016] [error] [client 50.37.195.225] File does not exist: /var/www/admin
[Thu Sep 29 20:08:34 2016] [error] [client 167.88.117.13] (13)Permission denied: file permissions deny server access: /var/www/index.html
[Thu Sep 29 20:08:35 2016] [error] [client 167.88.117.13] File does not exist: /var/www/favicon.ico, referer: http://drakoni.tech/
[Thu Sep 29 20:08:42 2016] [error] [client 167.88.117.13] PHP Parse error:  syntax error, unexpected '[' in /var/www/index.php on line 38
[Thu Sep 29 20:08:49 2016] [error] [client 167.88.117.13] File does not exist: /var/www/admin
[Thu Sep 29 20:08:59 2016] [error] [client 50.37.195.225] File does not exist: /var/www/admin
[Thu Sep 29 20:09:16 2016] [error] [client 167.88.117.13] PHP Warning:  Unknown: failed to open stream: Permission denied in Unknown on line 0
[Thu Sep 29 20:09:16 2016] [error] [client 167.88.117.13] PHP Fatal error:  Unknown: Failed opening required '/var/www/images.php' (include_path='.:/usr/share/php:/usr/share/pear') in Unknown on line 0
[Thu Sep 29 20:10:39 2016] [error] [client 167.88.117.13] PHP Warning:  Unknown: failed to open stream: Permission denied in Unknown on line 0
[Thu Sep 29 20:10:39 2016] [error] [client 167.88.117.13] PHP Fatal error:  Unknown: Failed opening required '/var/www/images.php' (include_path='.:/usr/share/php:/usr/share/pear') in Unknown on line 0
[Thu Sep 29 20:10:45 2016] [error] [client 167.88.117.13] File does not exist: /var/www/admin
[Thu Sep 29 20:10:47 2016] [error] [client 167.88.117.13] File does not exist: /var/www/admin
[Thu Sep 29 20:14:30 2016] [error] [client 167.88.117.13] (13)Permission denied: file permissions deny server access: /var/www/index.html
[Thu Sep 29 20:14:34 2016] [error] [client 167.88.117.13] PHP Parse error:  syntax error, unexpected '[' in /var/www/index.php on line 38
[Thu Sep 29 20:15:44 2016] [error] [client 50.37.195.225] PHP Parse error:  syntax error, unexpected '[' in /var/www/index.php on line 38
[Thu Sep 29 20:15:45 2016] [error] [client 50.37.195.225] PHP Parse error:  syntax error, unexpected '[' in /var/www/index.php on line 38
[Thu Sep 29 20:15:45 2016] [error] [client 50.37.195.225] PHP Parse error:  syntax error, unexpected '[' in /var/www/index.php on line 38`

**Comment by gnosticJade** [comment]
We only test past PHP 5.6. You'll need to update to a more recent version than 5.3.

**Comment by darknessresides** [comment]
It's now on PHP5.6

**Comment by darknessresides** [comment]
Or not... I installed PHP 5.6 and it still says 5.3

**Comment by darknessresides** [comment]
Doing a full reinstall of the OS; Will report back shortly.

**Comment by darknessresides** [comment]
Installed and running 5.6 and still the same error even though phpinfo.php shows wrong version of PHP installed. Fresh install of OS and only installed 5.6

If either of you want a crack at it to speed this up I'll send you connection info to it to fix it first hand

**Comment by gnosticJade** [comment]
@darkresides: Giving out administrator credentials is a poor idea. Try adding a the following to your VHost config.

```
<Directory /var/www/html>
        AllowOverride All
</Directory>
```

If that doesn't work, I spun up a VM of Ubuntu Server 12.04.5 to give you a step by step. You can see it [here](https://gist.github.com/gnosticJade/75de4da52a97ebd20a1c151242c0ab0b).

**Comment by darknessresides** [comment]
Thank you and it's finally fixed. On the image previews is there a way to remove the IP address it came from so no one can see it outside of the admin area? EDIT: Never mind just removed it from panel_admin.php and that did the trick

**Comment by Pips801** [comment]
Yes, Admin panel -> settings -> Viewer -> uncheck "Show IP"

**Comment by Pips801** [comment]
I do not recommend editing any of the files outside of /lib/templates unless you really know what you're doing.

**Comment by darknessresides** [comment]
Is there a way to say force the view to go directly to the extension of the file to make it easier to link images through bbcode on forums?

**Comment by gnosticJade** [comment]
Add /view to the link. If the forums require the image to be in an image format, you can add this to the .htaccess:
`RewriteRule ([^/]+)/?(view)?.png ./index.php?id=$1&action=$2 [L]` above `RedirectMatch 403 \/lib\/`

Which would result in images being directly viewable at `yoursite.com/randomstring/view` _or_ `yoursite.com/randomstring/view.png`
