### ISSUE TITLE
Drawing in region capture doesn't capture right in places

### ISSUE THREAD

**Issue by Alice-Cheshire** [UploadX/UploadX#25]
If you region capture an area but then draw text and such outside those areas, they don't get added to the resulting image unlike how you might expect. For example:

![factorio_2018-01-13_12-13-51](https://user-images.githubusercontent.com/13973188/34909754-0b67072a-f85c-11e7-9cbe-dd32da406b4a.png)

You can see along the top section and bottom left that there were arrows drawn from outside the captured areas. There was also some text there too. None of which was captured and there was no indication at all that this would be the case.

**Comment by Pips801** [comment]
@Alice-Cheshire, this is the github repository for a ShareX custom uploader, not ShareX itself. Please post your issues in the github repository for ShareX.

**Comment by Alice-Cheshire** [comment]
Whoops, I completely misread the url. Sorry about that!
